stages:
  - debug
  - build
  - test

# -----------------------------------
# Imagen base + Docker-in-Docker
# -----------------------------------
image: docker:27

services:
  - name: docker:27-dind
    command: ["--host=tcp://0.0.0.0:2375", "--tls=false"]

# -----------------------------------
# Variables globales
# -----------------------------------
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

  POSTGRES_DB: app
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/app
  DJANGO_SETTINGS_MODULE: core.settings.dev
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

# -----------------------------------
# Debug (verificar entorno)
# -----------------------------------
debug:
  stage: debug
  script:
    - whoami
    - which docker
    - docker version
    - pwd

# -----------------------------------
# Build backend
# -----------------------------------
build-backend:
  stage: build
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/backend:latest ./Microservicio
    - docker push $CI_REGISTRY_IMAGE/backend:latest

# -----------------------------------
# Build frontend
# -----------------------------------
build-frontend:
  stage: build
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/frontend:latest ./frontend
    - docker push $CI_REGISTRY_IMAGE/frontend:latest
    
# -----------------------------------
# Test frontend Angular
# -----------------------------------
frontend-tests:
  stage: test
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker run --rm $CI_REGISTRY_IMAGE/frontend:latest sh -c "
        npm ci &&
        npm run test -- --watch=false --browsers=ChromeHeadless
      "

# -----------------------------------
# Test backend Django
# -----------------------------------
backend-tests:
  stage: test
  services:
    - name: postgres:15
      alias: postgres
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker run --rm --network "$CI_JOB_NETWORK" -e POSTGRES_DB=$POSTGRES_DB -e POSTGRES_USER=$POSTGRES_USER -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -e DATABASE_URL=$DATABASE_URL $CI_REGISTRY_IMAGE/backend:latest sh -c "python manage.py migrate && pytest"




