FROM node:20-bullseye

ENV CHROME_BIN=/usr/bin/google-chrome

# Instalar Chromium y dependencias
RUN apt-get update && apt-get install -y \
    chromium \
    chromium-driver \
    ca-certificates \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libgbm1 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
    --no-install-recommends \
 && rm -rf /var/lib/apt/lists/*

ENV CHROME_BIN=/usr/bin/chromium

WORKDIR /app

# Cache de dependencias
COPY package*.json ./
RUN npm ci

# Copiar el resto
COPY . .

CMD ["npx", "ng", "test", "--watch=false", "--browsers=ChromeHeadless"]

