FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip

RUN pip install \
    django==4.2 \
    djangorestframework \
    psycopg2-binary \
    python-dotenv

COPY . /app
